apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ap28ltf4s-dotnet-basic
  janus-idp.io/tekton: ap28ltf4s-dotnet-basic
  backstage.io/kubernetes-id: ap28ltf4s-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ap28ltf4s-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
